public final class z {
   public boolean[] a = new boolean[100];
   public int a;
   public int b;
   public long a;
   public int c;
   public int d;
   public int e;
   public int f;
   public int g;
   public int h;
   public int i;
   public int j;
   public int k;
   public int l;
   public int m;
   public int n;
   public int o;
   public int p;
   public int q;
   public cl a;
   public cl b;
   public bd[] a;
   public int[] a;
   public boolean[] b = new boolean[11];
   public boolean[] c = new boolean[11];
   public int r;
   public int s;
   public int t;
   public int u;
   public boolean[] d = new boolean[22];
   public int v;
   public boolean[] e = new boolean[22];
   public int w;
   public long b;
   public int x;
   public int y;
   public int z;
   public int A;
   public int B;
   public int C;
   public int D;
   public int E;
   public int F;
   public int G;
   public boolean a = false;
   public boolean b = false;
   public boolean c = false;
   public boolean d = false;
   public boolean e = false;
   public boolean f = false;
   public boolean g = false;
   public boolean h = false;
   public boolean i = false;
   public boolean j = false;
   public boolean k = false;
   public boolean l = false;
   public boolean m = false;
   public boolean n = false;
   public boolean o = false;
   public boolean p = false;
   public boolean q = false;
   public boolean r = false;
   public boolean s = false;
   public boolean t = false;
   public boolean u = false;
   public boolean v = false;
   public boolean w = false;
   public boolean x = false;
   public boolean y = false;
   public boolean z = false;
   public boolean A = false;
   public long c = 0L;
   public long d = 0L;
   public ch a;
   public bd a;
   public cs a;
   public h[] a;
   public bp[] a;
   public ca[] a;
   public String[] a;
   public int H;
   public int I;
   public byte[] a;
   public int J;
   public boolean[] f;
   public int[] b;
   public int[] c;
   public byte[] b;
   public byte[] c;
   public String a;

   public final String toString() {
      return "Playing time: \t\t" + bc.a(this.a) + "\n" + "Level: \t\t" + this.e + "\n" + "Credits: \t\t" + this.a + "\n\n" + "Rating: \t\t" + this.b + "\n" + "Kills: \t\t" + this.c + "\n" + "MissionCount: \t\t" + this.d + "\n" + "LastWorth: \t\t" + this.f + "\n" + "StationsVisited: \t\t" + this.l + "\n";
   }
}
